version: "3.7"
services:
    #--------------------------------------------------------------------------
    # Application Database service
    #--------------------------------------------------------------------------
    fastcve:
        image: "fastcve:${DOCKER_TAG:-latest}"

        container_name: fastcve

        command: postgres ${ENV_POSTGRES_CONF}

        build:
            context: $PWD
            dockerfile: $PWD/Dockerfile

        environment:
            - INP_ENV_NAME
            - POSTGRES_PASSWORD
            - FCDB_USER
            - FCDB_PASS
            - FCDB_WEB_PARAMS=--host 0.0.0.0 --port 8000 --workers 4
            - NVD_API_KEY

        volumes:
            - vol_fastcve_db:/var/lib/postgresql/data
              #- ./config/setenv/:/fastcve/config/setenv
            - ./:/tmp

        ports:
            - "6630:5432"
            - "8000:8000"

        networks:
            - backend

#------------------------------------------------------------------------------
# Definition of networks used
#------------------------------------------------------------------------------
networks:
    backend:

#------------------------------------------------------------------------------
# Definition of docker volumes
#------------------------------------------------------------------------------
volumes:
    vol_fastcve_db:     # DB data for the vuln DB
